language: go

go:
  - "1.8.3"

env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Chanhun Jeong"
    - GIT_EMAIL="keyolk@gmail.com"
    - SOURCE_DIR="public"
    - BUILD_BRANCH="hugo"
    - DEPLOY_BRANCH="master"

install:
  - go get -u -v github.com/spf13/hugo

script:
  - git submodule update --init --recursive
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: $(GITHUB_TOKEN)
    local_dir: public
    skip_cleanup: true
    on:
      branch: master
