language: go

go:
  - "1.8.3"

env:
  global:
    - GIT_NAME="Chanhun Jeong"
    - GIT_EMAIL="keyolk@gmail.com"
    - SOURCE_DIR="public"
    - BUILD_BRANCH="hugo"
    - DEPLOY_BRANCH="master"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - git submodule update --init --recursive
  - hugo

deploy:
  - provider: pages
    github_token: ${GITHUB_TOKEN}
    local_dir: public
    skip_cleanup: true
    target_branch: master
    on:
      branch: hugo
