contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

canonifyURLs = true
baseurl = "https://keyolk.github.io"
title = "keyolk's page"

languageCode = "ko-KR"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir= true
enablegitinfo = true

theme = "hugo-theme-learn"
disqusShortname = "keyolk"
googleAnalytics = "UA-77710672-1"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[taxonomies]
  tag = "tags"

[params]
  editURL = "http://prose.io/#keyolk/keyolk.github.io/edit/hugo/content/"
  author = "keyolk"
  description = "hugo contents for keyolk.github.io"
  themeVariant = "blue"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/keyolk"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-linkedin'></i> LinkedIn"
url = "https://linkedin.com/in/keyolk"
weight = 11

[Languages]
[Languages.ko]
title = "Personal Documentation"
weight = 1
languageName = "Korean"
