baseurl = "https://keyolk.github.io"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
title = "keyolk's page"
canonifyURLs = true
languageCode = "ko-KR"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "hugo-theme-learn"
disqusShortname = "keyolk"
googleAnalytics = "UA-77710672-1"

[author]
  name = "keyolk"

[taxonomies]
  tag = "tags"

[params]
  editURL = "http://prose.io/#keyolk/keyolk.github.io/edit/hugo/content/"
  author = "keyolk"
  description = "hugo contents for keyolk.github.io"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = false
  ordersectionsby = "weight"
  themeVariant = "blue"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/keyolk"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-linkedin'></i> LinkedIn"
url = "https://linkedin.com/in/keyolk"
weight = 11
