baseurl = "https://keyolk.github.io"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
title = "keyolk's page"
canonifyURLs = true
languageCode = "ko-KR"
hasCJKLanguage = true

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "hugo-theme-learn"
disqusShortname = "keyolk"
googleAnalytics = "UA-77710672-1"

[author]
  name = "keyolk"

[taxonomies]
  tag = "tags"

[params]
  description = "hugo contents for keyolk.github.io"
  author = "keyolk"
  showVisitedLinks = false
  search = true
  editURL = "http://prose.io/#keyolk/keyolk.github.io/edit/hugo/content/"
  menu = [ "workspace", "container", "system", "cloud", "architecture", "security", "language", "algorithm" ]
